openapi: 3.1.0

info:
  title: The CareerOS API
  description: The CareerOS server API documentation
  contact: {}
  version: 1.3.2
  license:
    name: CareerOS internal usage license
    url: https://github.com/CareerOS/openapi/blob/main/LICENSE_TCOS

servers:
  - url: https://backend-prod-tsalqjuvda-oc.a.run.app
    description: Production server

tags:
  - name: Careers
    description: Careers endpoint
  - name: Applications
    description: Kanban tiles

paths:
  # Public API section
  /public/v1/universities:
    $ref: paths/public/universities.yaml
  /public/v1/universities/{universityID}/providers:
    $ref: paths/public/universities_{universityID}_providers.yaml
  /public/v1/universities/{universityID}/providers/{providerName}:
    $ref: paths/public/universities_{universityID}_providers_{providerName}.yaml

  #  Applications
  /api/v1/applications:
    $ref: paths/applications/index.yaml

  #  Universities
  /api/v1/enroll:
    $ref: paths/universities/enroll.yaml
  /api/v1/self/university:
    $ref: paths/universities/self_university.yaml
  /api/v1/universities/{universityID}/students:
    $ref: paths/universities/university_{universityID}_students.yaml
  /api/v1/cohort/{cohortID}/students:
    $ref: paths/universities/cohorts_by_id_students.yaml
  /api/v1/university/{universityID}/cohorts:
    $ref: paths/universities/cohorts_by_university_id.yaml

  #  Companies
  /api/v1/companies:
    $ref: paths/companies/index.yaml
  /api/v1/companies/issaved:
    $ref: paths/companies/issaved.yaml
  /api/v1/companies/{id}:
    $ref: paths/companies/by_id.yaml
  /api/v1/companies/search/{name}:
    $ref: paths/companies/search_by_name.yaml

  #  Contacts
  /api/v1/contacts:
    $ref: paths/contacts/index.yaml
  /api/v1/contacts/issaved:
    $ref: paths/contacts/issaved.yaml
  /api/v1/contacts/{id}:
    $ref: paths/contacts/by_id.yaml
  /api/v1/contacts/{id}/email:
    $ref: paths/contacts/by_id_email.yaml
  /api/v1/contacts/bycompany/{id}:
    $ref: paths/contacts/bycompany_id.yaml
  /api/v1/contacts/bycompany/{id}/byuser/{userID}:
    $ref: paths/contacts/bycompany_id_byuser_id.yaml

  #  Favorite Companies
  /api/v1/companies/favorite:
    $ref: paths/favorite/index.yaml
  /api/v1/companies/favorite/{id}:
    $ref: paths/favorite/by_id.yaml

  #  Jobs
  /api/v1/jobs:
    $ref: paths/jobs/index.yaml
  /api/v1/jobs/{id}:
    $ref: paths/jobs/by_id.yaml
  /api/v1/jobs/issaved:
    $ref: paths/jobs/issaved.yaml

  # Resumes
  /api/v1/resume/base:
    $ref: paths/resumes/base.yaml
  /api/v1/resume/base/{baseResumeID}:
    $ref: paths/resumes/base_{resumeID}.yaml
  /api/v1/resume/tailored:
    $ref: paths/resumes/tailored.yaml
  /api/v1/resume/tailored/{tailoredResumeID}:
    $ref: paths/resumes/tailored_{resumeID}.yaml
  /api/v1/resume/templates:
    $ref: paths/resumes/templates.yaml
  /api/v1/resume/templates/{templateID}:
    $ref: paths/resumes/templates_{templateID}.yaml
  /api/v1/resume/score:
    $ref: paths/resumes/score.yaml

  #  Users
  /api/v1/login:
    $ref: paths/users/login.yaml
  /api/v1/users/{id}:
    $ref: paths/users/by_id.yaml
  /api/v1/users/self:
    $ref: paths/users/self.yaml
  /api/v1/users/contacts:
    $ref: paths/users/contacts.yaml
  /api/v1/users/contacts/{id}:
    $ref: paths/users/contacts_by_id.yaml

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
