type: object
properties:
  id:
    type: string
    description: Application ID
    example: ed96665b-211f-4a03-a5ca-cd4ac2d74647
  status:
    type: string
    enum:
      - saved
      - networking
      - applying
      - applied
      - interviewing
      - offer
      - archive
    description: Application status
  rating:
    type: integer
    enum:
      - 0
      - 1
      - 2
      - 3
    description: |
      The application's rating reflects how much the user excited about the company:
        0 - Unrated;
        1 - Mildly interested;
        2 - Interested;
        3 - Excited;
      The mapping is rendered on the frontend side.
  company_id:
    type: string
    description: Company ID
    example: 04a32379-f2fa-43cb-902f-5f0033677dfa
  company_name:
    type: string
    description: Company name
    example: Google
  industry:
    type: string
    description: Industry
  logo_url:
    type: string
    format: uri
    description: Logo URL
  linkedin_url:
    type: string
    format: uri
    description: LinkedIn URL
  jobs:
    type: array
    items:
      $ref: ./JobInfo.yaml
    description: List of jobs associated with the application
  updated_at:
    type: string
    format: date-time
    description: Time of last update (create, status change) of application tile.
required:
  - status
  - company_id
  - company_name
  - industry
  - logo_url
  - linkedin_url
  - jobs
