post:
  tags:
    - Resumes
  operationId: createBaseResume
  summary: Create base resume
  description: |
    This endpoint allows users to create a new base resume.
    Upon successful creation, the server responds with the newly created resume resource.
  requestBody:
    required: true
    content:
      multipart/form-data:
        schema:
          type: object
          properties:
            resume:
              type: string
              format: binary
  responses:
    201:
      description: Created
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/resumes/base_resume_response.yaml
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/UnauthorizedError.yaml
    500:
      $ref: ../../components/responses/InternalServerError.yaml

get:
  tags:
    - Resumes
  summary: Get base resumes
  description: Get base resumes list
  operationId: getBaseResumes
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: ../../components/schemas/resumes/base_resume_response.yaml
    401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/UnauthorizedError.yaml
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/errors/NotFoundError.yaml
    500:
      $ref: ../../components/responses/InternalServerError.yaml
