get:
  tags:
    - Careers
  operationId: getApplicationForStudent
  summary: Get application details for a student
  description: Returns application details for a student
  parameters:
    - name: studentId
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: ID of the student for whom to retrieve the application details
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/Application.yaml
    '400':
      $ref: ../../components/responses/IDValidationFailedError.yaml
    '401':
      $ref: ../../components/responses/UnauthorizedError.yaml
    '500':
      $ref: ../../components/responses/InternalServerError.yaml
